<script lang="ts">
	import { evolveSchedules } from './../scheduler/hillclimbing/evolveSchedules.ts';
	import { generateSchedulesFromHeuristics } from './../scheduler/hillclimbing/generator.ts';  
	import { scoreSchedule, validateSchedule } from './../scheduler/';
  import DataPreview from './DataPreview.svelte';

	import type { StudentPreferences, Activity, Schedule } from './../types.ts';
  import SetupSheets from './SetupSheets.svelte';

  import { Block, Icon } from "google-apps-script-svelte-components";  
  import { GoogleAppsScript } from "./gasApi";
  import { onMount } from "svelte";
  import { Button } from "contain-css-svelte";
  import { assignByActivity, assignByPeer } from '../scheduler';
 
  export let data : {
    studentPreferences: StudentPreferences[],
    activities: Activity[],
  };
  const readData = async () => {
    data = await GoogleAppsScript.readData();
  }
  let schedule : Schedule = [];
  let schedules : {
    schedule: Schedule,
    score: number,
    invalid : string | undefined,
    id : string,
  }[] = [];
  let error;
  let score;
  let invalid;
  let alg : string;

  function doGenerate () {
    let startNum = schedules.length;
    schedules = generateSchedulesFromHeuristics(10, data.studentPreferences, data.activities, schedules)
    console.log('Generated',schedules.slice(startNum),'new schedules');
    for (let s of schedules.slice(startNum)) {
        if (s.score > score || !score && !s.invalid) {
            schedule = s.schedule;
            score = s.score;
            alg = s.alg;
            invalid = s.invalid;
        }
    }
  }

  function doEvolve () {
    let startNum = schedules.length;
    schedules = evolveSchedules(schedules, data.studentPreferences, data.activities, 500)
    console.log('Generated',schedules.slice(startNum),'new schedules');
    for (let s of schedules.slice(startNum)) {
        if (s.score > score || !score && !s.invalid) {
            schedule = s.schedule;
            score = s.score;
            alg = s.alg;
            invalid = s.invalid;
        }
    }
  }


  function doAssignByActivity () {
    error = undefined;
    console.log('Got prefs',data.studentPreferences)
    try {
        schedule = assignByActivity(data.studentPreferences, data.activities);
        alg = 'activity'
    } catch (err) {
        error = err;
        score = 0;
    }
  }
  function doAssignByPeer () {
    error = undefined;
    console.log('Got prefs',data.studentPreferences)
    try {
        schedule = assignByPeer(data.studentPreferences, data.activities);
        alg = 'peer';
    } catch (err) {
        error = err;
        score = 0;
    }
  }
  
  $: score = data && scoreSchedule(schedule, data.studentPreferences);
  $: invalid = data && schedule && validateSchedule(schedule, data.activities);
  $: console.log('Schedule pool is:',schedules);
  $: console.log('Best Schedule:',schedule.slice(), score);
</script>

<div class="tester">
    <Button on:click={doGenerate}>Generate Some!</Button>
    <Button on:click={doEvolve}>Evolve Some!</Button>
    <Button on:click={doAssignByActivity}>Assign by Activity</Button>
    <Button on:click={doAssignByPeer}>Assign by Peer</Button>
    {#if error}
        <h2>Error</h2><div class="error">{error}</div>
    {/if}
    Score {score}
    {#if invalid}
    <h2>Invalid Schedule!
        {invalid}
    </h2>
    {/if}
    Generated by {alg}    
</div>

<style>
</style>

